### ISSUE TITLE
Upgrade to Python v3

### ISSUE THREAD

**Issue by lzomedia** [fatiherikli/klassify#10]
Hi in python 3.6 you need to have to import in different way 
public/klassify/klassify/backend/handlers.py

insted of from itertools import imap

have a look here 

https://stackoverflow.com/questions/30271712/i-cant-find-imap-in-itertools-in-python 
hope it works for you

**Comment by lzomedia** [comment]
How to use your own 
git clone 
Change 
public/klassify/klassify/backend/handlers.py
From
from itertools import imap
To
from itertools import *

Change line 133 in 

public/klassify/klassify/backend/handlers.py

`
total = sum(imap(int, counts))

`
to 

`total = sum(map(int, counts))`

**Comment by fatiherikli** [comment]
Done. Thanks!
